### ISSUE TITLE
Edit Group Error:  NotFoundHttpException

### ISSUE THREAD

**Issue by christill** [rydurham/L4withSentry#13]
There appears to be an error when you try and edit a group from the admin panel.

**Comment by rydurham** [comment]
I will look at this when I am back in my office - probably sometime early next week.

**Comment by rydurham** [comment]
I have not been able to recreate this issue.  Have you found out any more about what the problem is?

**Comment by christill** [comment]
Not yet, I can take a look when I get home and I will try to isolate it.

**Comment by cybexmind** [comment]
Hello, I have deleted a backslash from file  "\app\views\groups\index.blade.php" at line 24:
---Before---

```
<td><button class="btn" onClick="location.href='{{ URL::to('groups') }}/{{ $group-> id}}/edit/'">
```

---After---

```
<td><button class="btn" onClick="location.href='{{ URL::to('groups') }}/{{ $group-> id}}/edit'">
```

So no errors.
Sorry but I do not know how to submit changes on github: (

**Comment by rydurham** [comment]
Changes are submitted via [pull requests](https://help.github.com/articles/using-pull-requests).   

I will go ahead and remove that backslash.  Thanks!
