### ISSUE TITLE
'Remember me' not remembering me

### ISSUE THREAD

**Issue by ghost** [rydurham/L4withSentry#16]
Not sure if this is the place to do it (first time!) but the remember me function on the login doesn't remember me when I log off and come to login again.

**Comment by rydurham** [comment]
Are you logging out, or are you just closing the browser tab and re-opening it later?  The 'Remember Me' functionality keeps you logged in for an extended period of time, regardless of how often you close your browser.   By executing a log out, you are flushing the cookies set by Sentry, which means you will have to log in regardless. 

The 'remember me' functionality is not designed to auto-populate the login form with your credentials.
