### ISSUE TITLE
Implement Validation Service

### ISSUE THREAD

**Issue by rydurham** [rydurham/L4withSentry#18]

**Comment by rathodvikas10** [comment]
hi, you are a gr8 programmer. i want to know what pattern you have used to manage sessions and form validation.
i am not able to understand the Authority/Repo and Authority/Service classes and interface interactions
how validation service works.
Providing links to resources which explains this stuff would be of gr8 help thnx.

**Comment by rydurham** [comment]
The majority of the structure of this application comes from the book "Implementing Laravel" by Chris Fidao:  https://leanpub.com/implementinglaravel

That book was very helpful to me - I reccomend it strongly.

**Comment by J5Dev** [comment]
I will second that recommendation, a combination of that and Taylor's Apprentice to Artisan (https://leanpub.com/laravel) are absolute musts for any Laravel dev :)
