### ISSUE TITLE
filters.php or routes.php?

### ISSUE THREAD

**Issue by qcol** [rydurham/L4withSentry#2]
1. Filter Auth is in both files. Is it correct? Shouldn't it be only in filters.php? 
2. When we use Sentry, is it necessary in filters.php? Isn't it biult-in auth code? 

Route::filter('auth', function()
{
    if (Auth::guest()) return Redirect::route('login');
});

**Comment by rydurham** [comment]
Filters Auth should only be in the filters.php file, not in both.  

The Auth filter is still necessary regardless of what you use to power your authentication.

**Comment by rydurham** [comment]
This has been fixed via 8191c7fb99a104acd3dd959ec70d3cc6b0895060
