### ISSUE TITLE
update profile (first name, last name) as user issue

### ISSUE THREAD

**Issue by MaverickDev** [rydurham/L4withSentry#27]
Hey,

I am new to GitHub and found your code, which is GREAT!
I believe I have found an issue though.
After installing your code, which went smoothly, I keep getting the following error:

1) login as user@user.com
2) update profile (first name and last name)

Result: database is indeed updated but I get the following error:
Error: You are not allowed to do that.

After quickly investigating it seems to be due the "userId" being NULL return from database update (Post route).
I could be wrong though (I am new to all this).

Thanks

**Comment by rydurham** [comment]
Thanks!
