### ISSUE TITLE
Composer update RuntimeException Mockery

### ISSUE THREAD

**Issue by brunoAmado** [rydurham/L4withSentry#34]
I don´t know if the problem is mine but after doing the download of L4withSentry and running "composer update" I have this RuntimeException:
- Installing mockery/mockery (dev-master 23ca1a2)
  Cloning 23ca1a274fb8fd175101574ac81cd1b82f3d0489
  
  [RuntimeException]
  Failed to clone https://github.com/padraic/mockery.git, git was not found,
  check that it is installed and in your PATH env.
  
  sh: 1: git: not found

**Comment by brunoAmado** [comment]
I resolve with "sudo apt-get install git" 
sorry for the Issue but is maybe a good ideia to put this line in Installation tutorial.
Thank for this great repository.

**Comment by rydurham** [comment]
I have added a note in the readme mentioning the need for git.
