### ISSUE TITLE
missing register button in index

### ISSUE THREAD

**Issue by jack6800** [rydurham/L4withSentry#36]
Hi
Thank for your efforts, there is a minor issue in index, missing user register button though there is getRegister in user controller already.

**Comment by rydurham** [comment]
There is a 'Register' link in the default view, but it is only visible if you are not logged in.  

Are you using the most up to date version of the UserController? The 'getRegister'  method has been removed. Instead, the register action is handled by the 'create' method of UserController.php  

What version of this project are you using?

**Comment by jack6800** [comment]
Hi
Thank for your timely reply, I'm newbe in Laravel, learning for interesting.
I clone your software last month and doing git update just before report 
these issues.
So I assumed all program has been refresh to newest states?
Sorry if I "reinvent" fixed issues.

Jack

**Comment by rydurham** [comment]
No worries!  Look at the UserController in your project and compare it to the [UserController](https://github.com/rydurham/L4withSentry/blob/master/app/controllers/UserController.php) in the main repo - are they the same? If not try grabbing a fresh copy of the code and see if you run into the same issues.  

The problem you were having with the activation link (#38)  is similar - check to see if your version of `app/views/email/auth/welcome.blade.php` is the same as the one in the main repo and see if that resolves the problem.

**Comment by jack6800** [comment]
Hi Ryan
You are right, what in my clone are old version! I do see a Register 
button after a fresh installation, thanks.
Have no idea why my repository fail to sync/update with yours.
Would you kindness enough to point out where went wrong because I really 
don't want to waste your time and like to avoid such problem in the future.
Here is my clone steps:
1. git clone -b master git://github.com/rydurham/L4withSentry.git l4
2. CD l4, curl -sS https://getcomposer.org/installer | php
3. php composer.phar install
4. git remote rename origin upstream
5. git remote add origin https://github.com/jack6800/l4.git
6. git push -u origin master
7. git fetch upstream
8. git merge upstream/master
9. php composer.phar update

_I run git remote update before test your software._

No doubt a validation system is a base of all serious web application, a 
good administrate tools are very important, since your goal seems very 
clear "A demo of Sentry", so I believe there shall have a back-end tools 
to manage all kind of users/group and permissions, that is why I add a 
register button in Users page.

**Comment by rydurham** [comment]
It seems like your procedures should work.  I am not sure what happened, but if it is working now you should be all set.

**Comment by rydurham** [comment]
I am going to close this issue - have you been able to resolve the problem?

**Comment by jack6800** [comment]
Yes, thanks
