### ISSUE TITLE
Active an account

### ISSUE THREAD

**Issue by jack6800** [rydurham/L4withSentry#38]
Will response an error "A group could not be found with ID [1]." when try to active account by http://l4a/users/activate/13/LQExzWiU1qHRuQSGU4vio83ay4qU4B5xZW9lJr4CeQ (received from mail):

**Comment by rydurham** [comment]
I believe this is related to the problem you are having in #36. `.../users/activate/13/LQExzWiU1qHRuQSGU4vio83ay4qU4B5xZW9lJr4CeQ` is no longer a valid activation URL in the 2.0 version of this project - the only way you could have this URL generated is if you are using an outdated version of the `app/views/emails/auth/welcome.blade.php` file.   Make sure everything is up to date and see if that fixes the problem.
