### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by rbk008** [rydurham/L4withSentry#40]
Hi,
     I am getting this  error while trying to migrate

$ php artisan migrate
PHP Fatal error:  Class 'Patchwork\Utf8\Bootup' not found in E:\Localhost\Ampps\www\L4withSentry\boo
tstrap\autoload.php on line 46

And,
      The composer update is running out of time and showing this error,

$ composer update
Loading composer repositories with package information
Installing dependencies (including require-dev)
- Installing doctrine/common (dev-master ad26be7)
  Cloning ad26be7787690d50d572d39a8d2ba5f1542a6d8f
  
  [Symfony\Component\Process\Exception\ProcessTimedOutException]
  The process "git clone "git://github.com/doctrine/common.git" "E:\Localhost\Ampps\www\L4withSen
  try\vendor\doctrine/common" && cd /D "E:\Localhost\Ampps\www\L4withSentry\vendor\doctrine/commo
  n" && git remote add composer "git://github.com/doctrine/common.git" && git fetch composer" exc
  eeded the timeout of 300 seconds.

So can you suggest me the solution for this......Thank you

**Comment by rydurham** [comment]
It looks like you may be able to solve this issue by running `composer install` rather than `composer update`.  Or you could try `composer update --prefer-dist`

**Comment by rbk008** [comment]
Wow....thank you.....its working with "composer update --prefer-dist" and even migration working fine.....thank you again....

**Comment by rydurham** [comment]
No problem.
