### ISSUE TITLE
Update to Laravel 4.1

### ISSUE THREAD

**Issue by cafeconweb** [rydurham/L4withSentry#48]
Hi! after update of Laraverl 4.1, I go to users or groups in admin and it returns a FatalErrorException:  Call to undefined method Illuminate\Routing\Route::getParameter()  in app/filters.php line 49  $userId = $route->getParameter('users');

Thanks for the help.

**Comment by rydurham** [comment]
Hi,

You need to tweak your filters.php file to work with the changes in 4.1.   Take a look [here](https://github.com/rydurham/L4withSentry/blob/master/app/filters.php) to see what you need to change.

**Comment by cafeconweb** [comment]
Great! Thanks a lot!
