### ISSUE TITLE
small issue with layout

### ISSUE THREAD

**Issue by brunoAmado** [rydurham/L4withSentry#49]
In the Layout (L4withSentry/app/views/layouts/default.blade.php) when a click to the  email in the top-right  it's give a route error in the line 59 

`<a href="/users/{{ Session::get('userId') }}">`
 I use this and it's work : 
`<a href="{{URL::to('users')}}/{{ Session::get('userId') }}">`

but i see a problem when a click in the line of a user in the botton of "edit"  in the administrations index but my low ability don't help me to correct. 
line 27 of L4withSentry/app/views/users/index.blade.php
`<button class="btn btn-default" type="button" onClick="location.href='{{ action('UserController@edit', array($user->id)) }}'">Edit</button>`
Can someone help ?

**Comment by rydurham** [comment]
Hi,

The link you provided isn't working - can you clarify the problem you are having?

**Comment by brunoAmado** [comment]
how can i write code html in this comments ?

**Comment by rydurham** [comment]
Github supports markdown in the comments - see [here](https://help.github.com/articles/github-flavored-markdown) for more information.  Look at the part discussing 'fenced code blocks'.

**Comment by riemers** [comment]
@brunoAmado: I think easiest is to do:

```
<a href="/users/{{ Session::get('userId') }}">
```

To

```
<a href="users/{{ Session::get('userId') }}">
```
