### ISSUE TITLE
'Binput' not found"

### ISSUE THREAD

**Issue by newtonianb** [rydurham/L4withSentry#5]
What is Binput::get??
I can not find any reference to this in the Laravel doc, is this custom and where is it defined?

https://github.com/rydurham/L4withSentry/blob/master/app/controllers/UserController.php#L138

```
"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Binput' not found"
```

Thanks

**Comment by newtonianb** [comment]
Found it in app/libraries. my bad, thanks

**Comment by rydurham** [comment]
I should have mentioned something about that in the readme.  Technically the Binput library is not needed because Laravel takes care of a lot of those needs on its own.  I may update this repo to remove it all together.

**Comment by rydurham** [comment]
I have now removed all references to the Binput::library.
