### ISSUE TITLE
Ability to change email

### ISSUE THREAD

**Issue by rbruhn** [rydurham/L4withSentry#52]
Perhaps the ability to change the email address should be added as well? It's easy enough to add in SentryUser and the edit form view, but kind of stuck on where to alter the validation rules so "required|email|unique:users,email,:id" can be used. ID being replaced with the current user id. Any thoughts?

**Comment by rydurham** [comment]
You should be able to alter the rules for User creating/editing in the [UserFormLaravelValidator.php](app/Authority/Service/Form/User/UserFormLaravelValidator.php) file. Give that a shot and see if that works for you.

**Comment by rbruhn** [comment]
Yes, but the issue is retrieving the user id there for the exclusion rule. Perhaps overriding AbstractLaravelValidator "with" or "passes" methods inside UserFormLaravelValidator?

**Comment by rydurham** [comment]
Ah - yes; I see what you are saying. 

First add the `email` validation rules to the [UserFormLaravelValidator](app/Authority/Service/Form/User/UserFormLaravelValidator.php). Next, add this function to your [AbstractLaravelValidator](app/Authority/Service/Validation/AbstractLaravelValidator.php):

``` php
/**
* Modify Rules on the fly 
*
* @param string $rule 
* @param string $column DB Column to check against
* @param string $ignore 
* 
* @return \Authority\Service\Validation\AbstractLaravelValidator 
*/
public function updateUnique($rule, $column, $ignore)
{
    $this->rules[$rule] .= ',' . $column . ',' . $ignore;
    return $this; 
}
```

And then update the `valid()` function in your [UserForm](app/Authority/Service/Form/User/UserForm.php) as such:

``` php
/**
* Test if form validator passes
*
* @return boolean 
*/
protected function valid(array $input)
{
    return $this->validator->with($input)->updateUnique('email', 'email', $input['user_id'])->passes();
}
```

Something to that effect should work - you will need to tweak it for your situation.

**Comment by rbruhn** [comment]
Thanks, it works perfectly. Just changed $input['user_id'] to $input['id'].

**Comment by MisterMike** [comment]
Excuse me for hooking in, but I found this thread particularly interesting while starting to learn using this great project.

I get the following error when trying to implement the above modifications:

BadMethodCallException
Method [validateEmail,email,1] does not exist

What did I possibly miss?

**Comment by rbruhn** [comment]
Well, in my case I was looking to add the ability of changing an email. So I basically copied and pasted the lastName code in views/users/edit.blade.php and replaced with email.

In Authority/Repo/User/SentryUser.php, update method add the email:

``` php
// Update the user details
$user->first_name = e($data['firstName']);
$user->last_name = e($data['lastName']);
$user->email = e($data['email']);
```

My validation rules in UserFormLaravelValidator are:

``` php
protected $rules = array(
    'firstName' => 'alpha',
    'lastName' => 'alpha',
    'email' => 'required|min:4|max:32|email|unique:users',
);
```

Other than those changes, I make the ones suggested above.

**Comment by MisterMike** [comment]
Thank you a lot - I really forgot to modify SentryUser.php - now its working like a charm

Thanks!

**Comment by rydurham** [comment]
Excellent!
