### ISSUE TITLE
Error: After renaming "Admin" group

### ISSUE THREAD

**Issue by ghost** [rydurham/L4withSentry#64]
After renaming "Admin" group into anything else access to Admin group is lost.
User is getting kicked out the system, it is possible to login again, but everything stays "locked" - keep getting redirects to login page with "Error: Group not found." message.

**Comment by rydurham** [comment]
The [filters](https://github.com/rydurham/L4withSentry/blob/master/app/controllers/UserController.php#L50) used to control access to administrative privileges are hard coded to look for an "admins" group.  If you want to change the name of the admin group you will need to update it in the codebase as well.

**Comment by ghost** [comment]
Thanks for the prompt answer. Issue closed :)
