### ISSUE TITLE
English Language is Incomplete

### ISSUE THREAD

**Issue by jpg-gamepad** [rydurham/L4withSentry#66]
I just installed the repository locally and noticed most of the English language is incomplete, but Bulgarian isn't. Is there a quick way for me to fix this?

Thanks!

**Comment by rydurham** [comment]
The translation of the views hasn't quite been completed.  I just tagged [v2.2](https://github.com/rydurham/L4withSentry/tree/v2.2) which is the last stable version before that project began.  Using that version should solve your problem. You could also send a PR with more of the english language strings if you wanted.

**Comment by jpg-gamepad** [comment]
Thanks! I really like this project btw, I've tried a few other Authorization packages and this one seems to be the best one.

**Comment by rydurham** [comment]
Thank you!  
[Sentry](https://github.com/cartalyst/sentry) is doing the heavy lifting of course; I am just providing a bridge between Sentry and Laravel.  Have you looked at [Sentinel](https://github.com/rydurham/Sentinel)?  It provides the same codebase as L4withSentry, only in package form.

**Comment by jpg-gamepad** [comment]
I did take a look at it but it didn't have any views packaged with it and I felt I needed something I could work off of vs building from scratch. Do you recommend that I use that instead? The project I am working on is almost complete but it needed a good authorization system. Most of the ones I've seen didn't have some of the key components of an Auth system, like "Forgot Your Password", "Remember Me", and administrator roles.

**Comment by rydurham** [comment]
Sentinel comes with views that work with Bootstrap, which you can customize if you run `php artisan asset:publish rydurham/sentinel`.  Eventually I am going to provide a couple different "themes" with the sentinel package, but I am not sure when I will get around to that.

Sentinel will be the easiest way to integrate with an existing app.  Using L4withSentry will allow you more flexibility in the long run.

**Comment by jpg-gamepad** [comment]
I'll check it out. It's probably exactly what I am looking for, but I kind of prefer my Auth packages have views in the 'app/views' folder.
