### ISSUE TITLE
Any reason why bumping laravel from 4.1.* to 4.2.* would be a problem?

### ISSUE THREAD

**Issue by LarryEitel** [rydurham/L4withSentry#68]
```
  - Removing laravel/framework (v4.1.30)
  - Installing laravel/framework (v4.2.6)
```

No immediate errors noticed.

**Comment by rydurham** [comment]
No particular reason - I just have not gotten around to upgrading the repo.

**Comment by rydurham** [comment]
At some point I will upgrade the entire repo to 4.2, but I haven't been
able to yet.
ᐧ

**Comment by rydurham** [comment]
Take a look at release 2.3 - it has been upgraded to Laravel 4.2 and Bootstrap 3.2
