### ISSUE TITLE
"Call to a member function hasAccess() on a non-object" on some url's when not logged in

### ISSUE THREAD

**Issue by erfanimani** [rydurham/L4withSentry#7]
In app/controllers/UserController.php - and a couple of other places - 

`if ( $currentUser->hasAccess('admin') || $currentUser->getId() == $id)`

should become

`if ( Sentry::check() && ( $currentUser->hasAccess('admin') || $currentUser->getId() == $id))`

according to http://docs.cartalyst.com/sentry-2/authentication/helpers#check-if-the-user-is-logged-in

**Comment by rydurham** [comment]
The Sentry::check() call is there, it is just usually a line or two before the hasAccess() call.
