### ISSUE TITLE
Pull this codes in workbench

### ISSUE THREAD

**Issue by lgt** [rydurham/L4withSentry#70]
Hi,

first of all thanks for this nice package. I wonder what would be best way to pull all of this codes in a workbench? To make a hybrid from this package and <a href="https://github.com/davzie/laravel-bootstrap">this</a>

**Comment by rydurham** [comment]
You may want to take a look at my [Sentinel](github.com/rydurham/Sentinel) package - it contains all of this code in Laravel Package form.

**Comment by lgt** [comment]
Thanks this is what I was searching
