### ISSUE TITLE
l5 With Sentry

### ISSUE THREAD

**Issue by ideadx** [rydurham/L4withSentry#73]
Any change to get Sentry with Laravel 5?

**Comment by rydurham** [comment]
I am not planning on updating this repo for Laravel 5, however, my [Sentinel](https://github.com/rydurham/Sentinel) package is available for L5 and is probably the fastest way to get up and running with Sentry.

**Comment by ideadx** [comment]
Thanks @rydurham. I just got the package installed and working like Charm :)
Thanks again for great work.

**Comment by rydurham** [comment]
Absolutely!  I am glad it has worked for you!
