### ISSUE TITLE
L5withSentry

### ISSUE THREAD

**Issue by ghost** [rydurham/L4withSentry#74]
Is there any forecast for launch L5withSentry ?

**Comment by rydurham** [comment]
I don't currently have any plans to migrate this repo to Laravel 5.  However, you can use my [Sentinel](https://github.com/rydurham/Sentinel) package to achieve the same thing, and it does work with Laravel 5.

**Comment by ghost** [comment]
Do you considers L4 as security and good as L5 ?

**Comment by rydurham** [comment]
Depends on what you mean.  If you are smart about what you are doing, I think both L4 and L5 have equally strong security.  However, L5 allows developers to have much more specific control over how that security is controlled and implemented (espeically with the middeware options.)

**Comment by ghost** [comment]
middeware options are really very interesting ....
If you can help me I'll be very grateful. Im trying to install in L5 the providers "RepoServiceProvider" and "FormServiceProvider" the same way you used in L4withSentry, but I dont know this dont work when i run de composer update; "Error Output: PHP Fatal error:  Class  App\Authority\Repo\RepoServiceProvider' not found in  var/www/laravel5sentry/vendor/laravel/framework/src/Illuminate/Foundation/Prov  
  iderRepository.php" 
Do you already used them at some L5 project?

**Comment by rydurham** [comment]
Rather than trying to modify this repo to work with L5, it will be easier to start with a clean L5 application and then install my Sentinel package - you will get all the same functionality.   The instructions on that repo page will walk you through the entire process of setting it up.

**Comment by ghost** [comment]
Very very interesting. work very well  :) thank you

**Comment by thecodingwhale** [comment]
this would be good! start from scratch! :+1:
